import Conway7.Setup
import Mathlib.Data.Fintype.Pi
import Mathlib.Data.Fintype.Prod

/-!
# Generic glue for the case analysis

The case analysis (`Conway7/Gen/*.lean`, generated by `scripts/gen_core.py`) uses the
rank-4 factorization `IsOrbitMatrix.factor_apply` with explicit certificates `(S, Adj, D)`.
This file states the factorization in the two shapes that are used:

* `fac_mm`, `fac_mj`: a mixed index `m` (`u m = 0`) against a basis `S` of indices in `A ∪ B`;
* bounded entries: every entry of `C` is the cast of a natural number `< 5`.
-/

open Matrix Finset

namespace Conway7

variable {C : Matrix (Fin 12) (Fin 12) ℤ}

namespace IsOrbitMatrix

variable (hC : IsOrbitMatrix C)
include hC

lemma G_mj {m j : Fin 12} (hm : 6 ≤ m.val) (hj : j.val < 6) : G C m j = 3 * C m j - 4 := by
  rw [G_apply, if_neg (ne_of_ge6 m hm j hj), u_of_ge6 m hm]; ring

lemma G_jm {m j : Fin 12} (hm : 6 ≤ m.val) (hj : j.val < 6) : G C j m = 3 * C m j - 4 := by
  rw [hC.G_symm, hC.G_mj hm hj]

lemma G_mm {m : Fin 12} (hm : 6 ≤ m.val) : G C m m = 8 := by
  rw [G_apply, if_pos rfl, hC.diag, u_of_ge6 m hm]; ring

/-- Factorization at `(m, m)` for a mixed index `m` and a basis `S ⊂ A ∪ B`. -/
theorem fac_mm (S : Fin 4 → Fin 12) (Adj : Matrix (Fin 4) (Fin 4) ℤ) (D : ℤ) (hD : 0 < D)
    (hAdjT : Adjᵀ = Adj) (hAdj : Adj * GS S C = D • 1) (hS : ∀ s, (S s).val < 6)
    (m : Fin 12) (hm : 6 ≤ m.val) :
    D * 8 = ∑ t, (∑ s, (3 * C m (S s) - 4) * Adj s t) * (3 * C m (S t) - 4) := by
  have h := hC.factor_apply S Adj D hD hAdjT hAdj m m
  rw [hC.G_mm hm] at h
  rw [h]
  refine Finset.sum_congr rfl (fun t _ => ?_)
  rw [hC.G_jm hm (hS t)]
  congr 1
  refine Finset.sum_congr rfl (fun s _ => ?_)
  rw [hC.G_mj hm (hS s)]

/-- Factorization at `(m, j)` for a mixed index `m` and `j ∈ A ∪ B`. -/
theorem fac_mj (S : Fin 4 → Fin 12) (Adj : Matrix (Fin 4) (Fin 4) ℤ) (D : ℤ) (hD : 0 < D)
    (hAdjT : Adjᵀ = Adj) (hAdj : Adj * GS S C = D • 1) (hS : ∀ s, (S s).val < 6)
    (m : Fin 12) (hm : 6 ≤ m.val) (j : Fin 12) (hj : j.val < 6) :
    D * (3 * C m j - 4) = ∑ t, (∑ s, (3 * C m (S s) - 4) * Adj s t) * G C (S t) j := by
  have h := hC.factor_apply S Adj D hD hAdjT hAdj m j
  rw [hC.G_mj hm hj] at h
  rw [h]
  refine Finset.sum_congr rfl (fun t _ => ?_)
  congr 1
  refine Finset.sum_congr rfl (fun s _ => ?_)
  rw [hC.G_mj hm (hS s)]

/-- Every entry is the cast of a natural number `< 5`. -/
lemma nat5 (i j : Fin 12) : ∃ n : Fin 5, C i j = ((n : ℕ) : ℤ) := by
  refine ⟨⟨(C i j).toNat, ?_⟩, ?_⟩
  · have h1 := hC.le4 i j
    have h0 := hC.nonneg i j
    omega
  · simp [Int.toNat_of_nonneg (hC.nonneg i j)]

end IsOrbitMatrix

/-- the `i`-th coordinate of `v`, as an integer -/
def zc {n : ℕ} (v : Fin n → Fin 5) (i : Fin n) : ℤ := ((v i : ℕ) : ℤ)

/-- the exact quotient used to recover an entry from a linear equation `D (3 w - 4) = L` -/
def wv (L D : ℤ) : ℤ := (L + 4 * D) / (3 * D)

/-- `ℤ`-division recovers an exact quotient. -/
lemma ediv_of_mul_eq {D L w : ℤ} (hD : 0 < D) (h : D * (3 * w - 4) = L) : wv L D = w := by
  subst h
  unfold wv
  have : D * (3 * w - 4) + 4 * D = (3 * D) * w := by ring
  rw [this, Int.mul_ediv_cancel_left _ (by omega)]

end Conway7
